/**
 * One-shot local setup: writes .env.local with sane dev defaults.
 *
 * Exists because the most common first-run error is
 *   "DATABASE_URL is not set. Copy .env.example to .env.local and configure it."
 * which stops people before they see anything run. This script removes the
 * manual step:
 *
 *   bun run setup                    no-password local URL (trust auth)
 *   bun run setup -- mypassword      URL with the password embedded
 *   bun run setup -- cockroach       commented CockroachDB template instead
 *
 * Never overwrites an existing .env.local. AUTH_SECRET is generated with
 * node:crypto (works on Windows without openssl). The demo login flags are
 * enabled for local development only — SECURITY.md documents that they must
 * stay unset in production.
 */
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { randomBytes } from "node:crypto";
const TARGET = resolve(process.cwd(), ".env.local");

/* argv notes (tested with bun, `bun run`, tsx and npm):
   - `bun setup-env.ts -- mypass`  -> slice(2) = ["mypass"]  ("--" is consumed)
   - `bun run setup -- mypass`      -> tsx receives ["mypass"]
   - `bun run setup -- cockroach`   -> ["cockroach"]
   Drop any stray separators and the script path itself, then take the first
   non-flag token as the password. */
const args = process.argv
  .slice(2)
  .filter((a) => a !== "--" && !a.endsWith("setup-env.ts"));
const wantsCockroach = args.includes("cockroach");
const password = args.find((a) => a !== "cockroach" && !a.startsWith("-"));

if (existsSync(TARGET)) {
  console.log("✔ .env.local already exists — leaving it untouched.");
  console.log("  To start over: delete it and run  bun run setup  again.");
  process.exit(0);
}

const secret = randomBytes(32).toString("base64");

const dbLine = wantsCockroach
  ? "# TODO: paste your CockroachDB General connection string here\nDATABASE_URL=postgresql://<user>:<password>@<cluster>.cockroachlabs.cloud:26257/hackmate?sslmode=verify-full"
  : `DATABASE_URL=postgres://postgres${password ? `:${password}` : ""}@127.0.0.1:5432/hackmate`;
const dbUrl = dbLine.split("\n").pop()!.replace(/^DATABASE_URL=/, "");

const contents = `# Generated by  bun run setup  — local development defaults.
# Production values belong in your Vercel dashboard, never in this file.

${dbLine}
AUTH_SECRET=${secret}
AUTH_URL=http://localhost:3000
# Replace with your own email to keep admin rights on your real account:
ADMIN_EMAILS=dev@hackmate.local

# DEV ONLY: enables the "Quick dev sign-in" button on the login page.
ALLOW_DEMO_LOGIN=true
NEXT_PUBLIC_ALLOW_DEMO_LOGIN=true

# Optional integrations (app degrades gracefully when unset):
# AUTH_GITHUB_ID= / AUTH_GITHUB_SECRET=        GitHub sign-in
# RESEND_API_KEY= / EMAIL_FROM=                email magic links
# PUSHER_APP_ID= / PUSHER_KEY= / PUSHER_SECRET= / PUSHER_CLUSTER=   realtime chat
# NEXT_PUBLIC_PUSHER_KEY= / NEXT_PUBLIC_PUSHER_CLUSTER=
# BLOB_READ_WRITE_TOKEN=                       avatar uploads
`;

writeFileSync(TARGET, contents, "utf8");

console.log("✔ created .env.local with local dev defaults");
console.log(`  DATABASE_URL = ${wantsCockroach ? "CockroachDB template (fill it in!)" : dbUrl}`);
console.log("  AUTH_SECRET  = generated (random 32 bytes)");
if (!password && !wantsCockroach) {
  console.log("");
  console.log("  NOTE: no Postgres password was provided.");
  console.log("  If your local Postgres uses a password, rerun:");
  console.log("     bun run setup -- yourpassword   (after deleting .env.local)");
}
console.log("");
console.log("Next steps:");
console.log("  bun run db:create     # create the hackmate database");
console.log("  bun run db:migrate    # apply schema migrations");
console.log("  bun run db:seed       # skills / roles / badges taxonomy");
console.log("  bun run db:seed:demo  # optional demo people, teams, hackathons");
console.log("  bun run dev           # http://localhost:3000");
